# Generated by Django 3.2.9 on 2021-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20211202_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishinfo',
            old_name='dish',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='dishitem',
            name='img',
            field=models.ImageField(upload_to='img/dishes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='img',
            field=models.ImageField(upload_to='img/ingredients/', verbose_name='Изображение'),
        ),
    ]
