# Generated by Django 3.2.9 on 2021-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20211211_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name'], 'verbose_name': 'Еда', 'verbose_name_plural': 'Список еды'},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='isEatable',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='isDish',
            field=models.BooleanField(default=False, verbose_name='Блюдо?'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='img',
            field=models.ImageField(upload_to='img/food', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='isIngredient',
            field=models.BooleanField(verbose_name='Может использоваться в качестве ингредиента'),
        ),
    ]
