# Generated by Django 3.2.9 on 2021-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_auto_20211202_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishinfo',
            name='count',
        ),
        migrations.RemoveField(
            model_name='ingredientinfo',
            name='count',
        ),
        migrations.AddField(
            model_name='dishinfo',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Вес (г)'),
        ),
        migrations.AddField(
            model_name='ingredientinfo',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Вес (г)'),
        ),
    ]
