# Generated by Django 3.2.9 on 2021-12-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_auto_20211214_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='isIngredient',
        ),
    ]
