# Generated by Django 3.2.9 on 2021-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20211208_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishitem',
            name='calories',
            field=models.PositiveIntegerField(default=100, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='dishitem',
            name='carbohydrates',
            field=models.FloatField(default=0, verbose_name='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='dishitem',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='dishitem',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки (г)'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='calories',
            field=models.PositiveIntegerField(default=100, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='carbohydrates',
            field=models.FloatField(default=0, verbose_name='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки (г)'),
        ),
    ]
