# Generated by Django 3.2.9 on 2021-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20211208_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishitem',
            name='visionname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Обозначение в CustomVision'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='visionname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Обозначение в CustomVision'),
        ),
        migrations.AlterField(
            model_name='dishitem',
            name='calories',
            field=models.PositiveIntegerField(default=10, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='calories',
            field=models.PositiveIntegerField(default=10, verbose_name='Калории'),
        ),
    ]
